data:
  data_csv: "data/raw/img/sports.csv"
  extracted: ["train", "valid", "test"]
  base_dir: "data/raw/img"
data_config:
  train_batch_size: 16
  dev_batch_size: 32
modeling:
  # See https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.callbacks.early_stopping.html
  early_stopping_cfg:
    monitor: val_loss
    patience: 3
    mode: min
  # See https://pytorch-lightning.readthedocs.io/en/latest/extensions/generated/pytorch_lightning.callbacks.ModelCheckpoint.html
  model_checkpoint_cfg:
    dirpath: "outputs/img/out_1/"
    filename: "{epoch}-{val_loss:.4f}-{val_f1:.4f}"
  # See https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.trainer.trainer.html
  trainer_cfg:
    max_epochs: 10
    precision: 16
  model_cfg:
    model_name: effnetb0
    is_pretrained: true
    learning_rate: 0.0001
  wandb:
    name: sport-iseng-1
    project: sport-iseng
